name: dealer-management-system
region: sfo3
services:
  - name: web
    source_dir: /
    github:
      repo: meibohuhu/dealer_management_unified_service
      branch: main
    build_command: rm -rf node_modules package-lock.json && npm install && npm run build:server
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    health_check:
      http_path: /health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: NODE_TLS_REJECT_UNAUTHORIZED
        value: "0"
      - key: USE_SQLITE
        value: "false"
      - key: API_BASE_URL
        value: "https://dealer-management-system-djlol.ondigitalocean.app/api"
      - key: DATABASE_URL
        value: "YOUR_DATABASE_URL_HERE"
      - key: SPACES_ENDPOINT
        value: "https://sfo3.digitaloceanspaces.com"
      - key: SPACES_BUCKET
        value: "dealermanagementsystem"
      - key: SPACES_REGION
        value: "sfo3"
      - key: SPACES_ACCESS_KEY_ID
        value: "YOUR_SPACES_ACCESS_KEY_ID_HERE"
      - key: SPACES_SECRET_ACCESS_KEY
        value: "YOUR_SPACES_SECRET_ACCESS_KEY_HERE"
      - key: SPACES_CDN_ENDPOINT
        value: "https://dealermanagementsystem.sfo3.cdn.digitaloceanspaces.com"

# External PostgreSQL cluster configuration
# The app will connect to your managed PostgreSQL cluster
# instead of using the built-in database component

# Spaces configuration will be set up separately via environment variables
